# Generated by Django 3.2.4 on 2021-07-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', help_text='The name of the publisher', max_length=50)),
                ('website', models.URLField(help_text='The Publisher website')),
                ('email', models.EmailField(help_text='Publishers email address', max_length=254)),
            ],
        ),
    ]
