# Generated by Django 3.2.4 on 2021-08-24 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210706_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover_image/'),
        ),
        migrations.AddField(
            model_name='book',
            name='sample',
            field=models.FileField(blank=True, null=True, upload_to='book_samples/'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='first_names',
            field=models.CharField(default='Demo', help_text="The contributor's first name or names.", max_length=50),
        ),
        migrations.AddField(
            model_name='contributor',
            name='last_names',
            field=models.CharField(default='User', help_text="The contributor's last name or names.", max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, verbose_name='ISBN number of the book.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(verbose_name='Date the book was published.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='The title of the book.', max_length=70),
        ),
        migrations.AlterField(
            model_name='bookcontributor',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('CO_AUTHOR', 'Co-Author'), ('EDITOR', 'Editor')], max_length=20, verbose_name='The role this contributor had in the book.'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='email',
            field=models.EmailField(help_text='The contact email for the contributor.', max_length=254),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='email',
            field=models.EmailField(help_text="The Publisher's email address.", max_length=254),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(help_text='The name of the Publisher.', max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='website',
            field=models.URLField(help_text="The Publisher's website."),
        ),
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(help_text='The Book that this review is for.', on_delete=django.db.models.deletion.CASCADE, to='review.book'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(help_text='The Review text.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date_edited',
            field=models.DateTimeField(help_text='The date and time the review was last edited.', null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='The the reviewer has given.'),
        ),
    ]
